name: MitaTowns
main: me.com.hutattedonmyarm.Mita.MitaTowns.MitaTowns
version: 1.0
author: hutattedonmyarm
commands:
  town:
    description: Town commands
    usage: /t [help|?]
    aliases: t
  resident:
    description: Player commands
    usage: /res [help|?]
    aliases: res
  plot:
    description: Plot commands
    usage: /p [help|?]
    aliases: p

permissions:
    MitaTowns.*:
        description: Gives access to all commands from MitaTowns
        children:
            MitaTowns.admin.*: true
            MitaTowns.manageAssistans: true
    MitaTowns.admin.*:
        description: MitaTowns admin commands
        children:
            MitaTowns.town.new: true
    MitaTowns.mod.*:
        description: MitaTowns mod commands
        children:
            MitaTowns.watchPerms: true
